---
title: Descriptif de la formation
date: "25 septembre 2024"
---


# Public ciblé

Personnels de bibliothèque contribuant à la formation des publics
Personnels spécialisés dans l'ingénierie pédagogique

# Objectifs

    Se familiariser avec les outils d'intelligence artificielle générative (IAG) utilisés par les étudiants et connaître d'autres outils plus spécialisés
    Appréhender les différentes manières dont les étudiants s'approprient ces outils dans leur travail quotidien
    Permettre aux étudiants d'aborder avec un esprit critique les productions d'une IAG
    Intégrer les IAG dans le socle de [compétences informationnelles](competences_informationnelles.md) à transmettre aux étudiants


# Compétences visées :

    Comprendre le fonctionnement des IA génératives
    Utiliser les IAG pour faciliter la [conception de supports pédagogiques](generer_quiz.md)
    Choisir l'outil le plus approprié pour la réalisation d'une tâche donnée
    Porter un discours éclairé et pondéré sur l'usage des IAG à l'Université auprès de la communauté étudiante et des enseignants

# Programme

    Maîtriser les [concepts essentiels](concepts_essentiels.md) : LLM, RAG, fine-turning, tokens, entraînement, prompts, hallucinations, etc..
    Utiliser les IAG pour [générer du code](generer_code.md), [des quiz](generer_quiz.md), pour trouver des idées...
    [Qualifier des usages](qualifier_usages.md) d'étudiants et de professionnels en tant que risques ou opportunités
    Utiliser les [IAG de façon responsable](enjeux_ethiques_environnementaux.md)

# Méthodes pédagogiques

    Usage d'outils destinés à faire de la pédagogie autour des IA
    Discussion collective (board) sur des cas d'usage des IAG par étudiants
    Elaboration collective (en sous-groupes avec mise en commun à la fin de la séance) d'activités destinées à insérer la maîtrise des IAG dans les compétences informationnelles et pour promouvoir l'esprit critique chez les étudiants vis-à-vis des productions réalisées au moyen d'IAG

# Pré-requis

Un [questionnaire](questionnaire.md) à remplir sera transmis au préalable pour mieux percevoir les attentes des stagiaires
Tarifs

    Convention université zone de compétence MCO : gratuit
    Hors convention université ou hors subvention DRAC - Formation d'une journée : 110 €

# Précisions sur le lieu de formation
Lieu de formation : (86) Université de Poitiers - MÉDIA CENTRE-OUEST
Contact téléphonique : 05.49.45.33.73