---
title: generer_quiz.md
---

---
title: Exercice générer un quiz
---

Le but de l'exercice va consister à générer un H5P à partir d'un texte.
Pour être réalisé, l'exercice nécessite que le logiciel logiquiz soit téléchargé sur l'ordinateur. 

1. Aller sur [le site de la Digitale](https://ladigitale.dev/logiquiz/#telecharger)
2. téléchargé l'archive zip sur le Bureau de votre ordinateur
3. Dézippez l'archive (clic droit sur l'archive > extraire les fichiers)
4. Pour exécuter le logiciel, suivez le chemin suivant dans l'arborescence : logiquiz-1.0.9éwindows > Logiquiz > logiquiz.exe 
5. Si le logiciel vous demande de modifier le parefeu, cliquer sur "annuler"

Vous êtes normalement en mesure à présent d'éditer des activités H5P. 

On va donc créer une série de questions à choix multiple à partir d'un [article disponible sur HAL](article.pdf)

Vous pouvez faire l'exercice en utilisant Chat GP ou [Poe et le modèle Claude 3.5 Sonnet](https://poe.com)

Encore une fois, ces outils ne sont pas précisément faits pour cela, mais on peut toujours les utiliser à cette fin, même si les résultats obtenus ne seront sans doute pas de qualité professionnelle : à vous d'apporter votre savoir-faire pédagogique :wink: 

Utilisez le signe + pour charger le document et faire en sorte qu'il soit traité par le chatbot en même temps que votre prompt. 

Vous devez obtenir au choix : 

un résumé de 10 lignes sous forme de texte à trous. 
une série de 3 questions à choix multiples comportant chacune 4 options. 

Etes-vous satisfait.e de ce que vous avez obtenu ? 

Si non, proposez une autre QCM. 
Si oui, demandez à Poe / ChatGPT ou autre... de formater le texte pour qu'il puisse être utilisé directement dans Logiquiz. 
