---
title: "Déroulé"
---


# Activités matin

Recul critique vis à vis de l'IA : comment aborder la question avec les étudiants. 
3 idées clé : 

- 1. l'Histoire de l'IA est déjà longue avant la venue de ChatGPT

voir [Histoire de l'IA avant ChatGPT](histoire_ia.qmd)

- 2. Le présent de l'IA ne se confond pas avec les IAG

qu'est-ce qu'entraîner un modèle : exemple avec une IA de classification : pinceaux et stylos (voir [classification](classification/classification.qmd))

- 3. ChatGPT n'est pas synonyme d'IAG. Chaque outil a ses propres spécificités, les outils ne sont pas interchangeables. La culture scientifique consiste à utiliser le bon outil pour la bonne tâche et à ne pas se focaliser sur un seul outil pour l'appliquer à tout. Parler d'IAG, c'est reparler de culture numérique et poser le problème. Si les étudiants ou les chercheurs utilisent les IAG de façon inappropriée, c'est d'abord par manque de culture numérique. 

Louis Derrac : parler d'IAG donne le prétexte aux formateurices de faire de la culture numérique avec leurs étudiants.









# Activités après-midi

- [Générer des quiz](generer_quiz.qmd)

- [générer du code](generer_code.qmd)

